### ISSUE TITLE
Missing localization

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2-module-reporting#118]
Not everything is localizable. Templates also are not.

**Comment by log1-c** [comment]
@nilmerg Would this cover that the CSV export of a report has the SLA values comma-separated if the webinterface is in german and point-separated if the webinterface is in english?
Imo the CSV export should always have the point-separated values (i.e. disregard the webinterface language/localization), because the CSV files get created with a comma as column separator.

If this is something that is not covered by this issue I will open a distinct one for that :)

**Comment by nilmerg** [comment]
Nope, that is definitely a different issue.
