### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-reporting#8]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
We are a PostreSQL shop mainly and use it for any backing resources within Icinga2/Icinagweb2.  We would like to utilize this existing DB store to add the Reporting module, rather than go through the pain of adding and maintaining another DB store (MySQL).

## Describe alternatives you've considered
Setting up our own reporting solution with Hadoop Hive, but that does not solve integration or schema issues that we would need to solve ourselves. Plus, this has great integration and automation we would love to use.

## Additional context
None for now.

**Comment by Philambdo** [comment]
Just for now i tried to fork it (https://github.com/Philambdo/icingaweb2-module-reporting-1) and added a basic postgres schema - that at least works for now. Not sane or safe but enough for testing.
I also had to fix column names and touch the corresponding php code because "end" is not a valid name for a column in postgres.
At the moment i'm not sure where to go from here. Where is your favourite line of communication/discussion ?
Here/IRC/Forum?

Greetings,
Florian

**Comment by lippserd** [comment]
Hi,

Thanks for the report. PostreSQL support is planned but we did not start to implement it yet.
@Philambdo cool stuff that you're working on this. Any chance to create a PR and we sort things out then?

Cheers,
Eric
